name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Console
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        path: ".ConsoleTeste/"
    - name: Setup .NET UnitTest
      with:
        dotnet-version: 6.0.x
        path: ".TesteUnitarioIdade/"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
